# .github/workflows/keep-alive.yml
name: Keep Server Warm

on:
  schedule:
    # every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake server
        run: |
          curl --fail --silent https://your-app-domain.onrender.com/status \
            || echo "Ping failed at $(date)"
